name: Input Information

on: push

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Directory and File
        run: |
          mkdir artifact
          echo 'printf("Hello world");' > artifact/sample.c

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d %H:%M:%S)"

      - name: push branch
        run: |
          branch_name_date="Auto/momotetu/${{ steps.date.outputs.date }}"
          git checkout -b $branch_name_date