name: C Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd ./src
          gcc -o .hello_world main.c

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello_world
          path: ./src

      - name: Show Current Directory
        run: pwd

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Show Current Directory
        run: tree .

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: hello_world

      - name: Change directory to src
        run: cd /home/runner/work/masamonstar/masamonstar/src

      - name: Deploy
        run: |
          ./hello_world