name: C Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Build C code
      run: gcc -o hello_world main.c
      working-directory: ./src
    - name: Execute binary
      run: ./hello_world
      working-directory: ./src