name: Input Information

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the branch name'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch
        run: |
          branch_name="${{ github.event.inputs.branch_name }}"
          git checkout -b $branch_name

      - name: Create Directory and File
        run: |
          mkdir artifact
          echo 'printf("Hello world");' > artifact/sample.c

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: fetch check branch
        run: |
          branch_name_date="Auto/test/${{ steps.date.outputs.date }}"

          git checkout -b $branch_name_date

      - name: push branch
        run: |
          git push --set-upstream origin $branch_name_date