name: Input Information

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the branch name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print current date and time
        run: echo "Current date: $(date '+%Y-%m-%d %H:%M:%S')"