name: Input Information

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the branch name'
        required: true
      comp_name:
        description: 'Enter the name'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch
        run: |
          branch_name="${{ github.event.inputs.branch_name }}"
          git checkout -b $branch_name

      - name: Search file for keyword
        run: |
          if grep -q "${{ github.event.inputs.comp_name }}" comp.json; then
            echo "EXIST"
          else
            echo "No EXIST"
          fi