name: C Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout JSON file
        uses: actions/checkout@v2

      - name: Show current directory
        run: |
          echo "Current directory: $(pwd)"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Create branch
        run: |
          branch_name="Auto/momotetu/${{ steps.date.outputs.date }}"
          git checkout -b $branch_name
          git push origin $branch_name

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build C code change
        run: sh build.sh
        working-directory: ./src

      - name: Execute binary
        run: ./hello_world
        working-directory: ./src

      - name: push branch
        run: |
          git push origin $branch_name
