name: C Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Build C code hello
      run: sh build.sh
      working-directory: ./src
    - name: Build C code change
      run: sh build.sh
      working-directory: ./bin
    - name: Execute binary hello
      run: ./hello_world
      working-directory: ./src
    - name: Execute binary change
      run: ./change_file
      working-directory: ./execute