name: C Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change directory to src
        run: cd ./src

      - name: Build
        run: gcc -o .hello_world main.c

      - name: Execute binary
        run: ./hello_world