name: Input Information

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print current date and time
        run: echo "Current date: \$(date '+%Y-%m-%d %H:%M:%S')"