name: C Build and Deploy

on:
  workflow_dispatch:
    inputs:
      input_base:
        description: 'If you want to do a base'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change directory to src
        run: cd ./src

      - name: Build
        run: gcc -o hello_world main.c

      - name: Execute binary
        run: ./hello_world